# Generated by Django 3.2.3 on 2021-06-19 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id_mecanico', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_mecanico', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id_trabajo', models.IntegerField(primary_key=True, serialize=False)),
                ('diagnostico', models.TextField()),
                ('valor', models.IntegerField()),
                ('fecha', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mecanico')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vehiculo')),
            ],
        ),
    ]
