# Generated by Django 3.2.3 on 2021-06-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='trabajos'),
        ),
    ]
