# Generated by Django 3.2.3 on 2021-06-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trabajo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='id_trabajo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
