# Generated by Django 3.2.3 on 2021-06-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_trabajo_id_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='diagnostico',
            field=models.CharField(max_length=100),
        ),
    ]
